### PR TITLE
Use footer links

### PR DESCRIPTION
**Pull request by sayanarijit**
Tool used: https://github.com/sayanarijit/md-footer

### CODE REVIEW

**Comment by sayanarijit** [comment]
@maximbaz I think it's now pretty close to offline docs. Can we package and use this?

**Comment by maximbaz** [comment]
Absolutely! We can package markdown files directly, we can also convert them to some other format if necessary, like html or man-page, from what I can see there is really no consensus - do you have personal preference? Would you find markdown files good for use?

**Comment by sayanarijit** [comment]
Great... html will require a browser. I'd prefer a format that's portable / widely supported, easy to navigate, and doesn't require a GUI tool like browser. We can search the docs using fzf and some key binding like `:h`.

**Comment by sayanarijit** [comment]
BTW [glow](https://github.com/charmbracelet/glow) is awesome. Checks out all the points ^.

**Comment by sayanarijit** [comment]
Nope.. Inter-document navigation [isn't supported as of now](https://github.com/charmbracelet/glow/issues/174).

**Comment by maximbaz** [comment]
Yep, okay, lets not over-think it, package markdown and let users read them or convert locally to whatever they want :)

**Pull request merged**
