### PR TITLE
Improve builtin search mode

### PR DESCRIPTION
**Pull request by noahmayr**
I switched the fuzzy matcher to the full skim matching engine and also added new messages to toggle between ranked or sorted search results.

Relates to discussion in #584.

### CODE REVIEW

**Comment by sayanarijit** [comment]
I'm not sure if I'd actually want to switch ranking at runtime. I think it's better to keep it a static boolean variable.

**Comment by sayanarijit** [comment]
Or maybe an enum variable if we have more than one ranking algorithm in the future.

**Comment by noahmayr** [comment]
The enum could be an idea, but I personally like being able to search for files and then decide how I want them ranked instead of having to edit my config file and reboot xplr for that.

We could still do a configuration for a default value and remove the option to change sorting while searching from the default init.lua but I don't see a problem with having the messages there for people who want that functionality (like with fzf's ctrl-r command where you can sort recent commands either by how well they match the query or chronologically by pressing `ctrl-z`).

**Comment by sayanarijit** [comment]
Ah got it... Sounds good then. As always, thanks for the pr.

**Comment by sayanarijit** [comment]
I think for now, we can go with `rank = true`. Later we can add one more param `ranking_algorithm: Option<Algorithm>`. None = whatever is the current default.

- Clangd
- SkimV1
- SkimV2

**Comment by noahmayr** [comment]
I've actually added the ranking enum and I've also added 2 options for search algorithms (since we have skim already anyways it's quite simple to expose that) but I'm running into a problem:

The current ranking + algorithm needs to be part of the explorer config to be available in the explore function since the config is not available there. 
That means we can't really add it to the global configuration unless we want to read it during init and then set that configuration on the initial explorer config.

**Comment by noahmayr** [comment]
I've added 2 possible search algorithms for now that are provided in a similar way from Skim as well as 2 search order options (ranked or sorted). 

I'm unsure about the SetAlgorithm message, it's mostly there to quickly try out different algorithms right now.

**Comment by erikLundstedt** [comment]
As someone who use fzf (skim has a less rememberable name and has some differing opinions/flags I think) for practically everything, this sounds amazing

**Comment by sayanarijit** [comment]
Let me try something...

**Comment by sayanarijit** [comment]
Had to add a breaking change (I think it's fine). Made the messages as flat as possible. Pls review.

**Comment by noahmayr** [comment]
I like it, I've made 2 small adjustments:
- Moved the search ranking/sorting inside the search algorithm
- CycleSearchAlgorithm only cycles between Fuzzy <-> Regex or FuzzyUnranked <-> RegexUnranked

**Comment by sayanarijit** [comment]
In that case, I think separating the alrogithm and ordering makes more sense. Pushed the same.

**Pull request merged**
