### PR TITLE
Use unsafe lua to allow c modules

### PR DESCRIPTION
**Pull request by sayanarijit**
Closes: https://github.com/sayanarijit/xplr/issues/309

### CODE REVIEW

**Comment by sayanarijit** [comment]
Hey @fhill2, can you please confirm if this works for your use case?

**Comment by fhill2** [comment]
non C modules are now loading but unable to find certain symbols.

This is the err msg:
(Require paths are showing as non default as I added the require paths manually to my luarocks installation before loading `luv` in the xplr lua environment.
```
 ERROR   runtime error: error loading module 'luv' from file '/home/f1/.cache/nvim/packer_hererocks/2.0.5/lib/lua/5.1/luv.so':
        /home/f1/.cache/nvim/packer_hererocks/2.0.5/lib/lua/5.1/luv.so: undefined symbol: lua_checkstack
```
Could this info help here?
Seems like this was fixed by [adding -Wl,-E to the list of linker options](https://github.com/envoyproxy/envoy/issues/2251#issuecomment-353726154).
this has to do with static linking and the fact that the binary needs to export the symbols that the SOs need](https://github.com/envoyproxy/envoy/issues/2251#issuecomment-353745168)

**Comment by khvzak** [comment]
Creating `.cargo/config` (inside the xplr project) with the following context:
```
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]
```
should solve the issue and expose symbols.

OR compile with:
```
$ cargo rustc --release --bins -- -C link-args='-rdynamic'
```

then you probably will get error: 
```
undefined symbol: luaL_openlibs
```
This is because xplr uses outdated `mlua v0.5`, this is fixed in `v0.6` (updating version in Crates.toml should be enough).

**Comment by fhill2** [comment]
@khvzak Thank you for the pointers, everything working now (still learning rust atm :D)
C modules are loading for me with this new commit, can use luv inside xplr lua environment. Perfect.

**Comment by sayanarijit** [comment]
Awesome! Thanks again 🙏

**Comment by sayanarijit** [comment]
The latest mlua feels so much faster :+1: 

@fhill2 Need your review one more time. I'll then create a new release.

**Comment by sayanarijit** [comment]
Merging this hoping everything runs fine.

**Comment by sayanarijit** [comment]
Published Published https://github.com/sayanarijit/xplr/releases/tag/v0.14.5

**Pull request merged**
