### PR TITLE
Add Default nix

### PR DESCRIPTION
**Pull request by GuilloteauQ**
Hello,

I created a small `default.nix` file for your project so i could install it on my NixOS system (as it is not (yet) in nixpkgs).
If you are interested here it is !

Nix(OS) users can then install `xplr` with the following command:
```
nix-env -i -f https://github.com/sayanarijit/xplr/tarball/main
```

### CODE REVIEW

**Comment by sayanarijit** [comment]
Great. Can you please add a reminder in `Cargo.toml` and `app.rs (VERSION)` to update the version?

**Comment by sayanarijit** [comment]
You may need to compile it to update `Cargo.lock`

**Comment by sayanarijit** [comment]
Hey @GuilloteauQ thanks for your contribution. So, how do you generate the `cargoSha256`? It doesn't seem like a normal `sha256`.

**Comment by GuilloteauQ** [comment]
So basically this `sha256` represents all the inputs of the rust app (versions of the deps, code, etc).
So changing the version will change the value of the `cargoSha256`.
In practice, for funding the hash, what we do is to build the nix package with a dummy `sha` (e.g. full of `0`) and wait for Nix to tell us that this incorrect and give us the right hash:

```sh
$ nix-build
...
hash mismatch in fixed-output derivation '/nix/store/j6aykbjq5n2vcisxazcrn38y3wprqjqy-xplr-vendor.tar.gz':
  wanted: sha256-0000000000000000000000000000000000000000000=
  got:    sha256-IyaYkHXmqXziXNK6uYU+XNNWA8a8S8cuMxkopps/9kk=
```
The correct hash is the `got: sha256-.......`
 
Some links:

[https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md#compiling-rust-applications-with-cargo](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md#compiling-rust-applications-with-cargo)

[https://discourse.nixos.org/t/how-exactly-is-cargosha256-computed/10727/3](https://discourse.nixos.org/t/how-exactly-is-cargosha256-computed/10727/3)

**Comment by sayanarijit** [comment]
After using all zeros, `nix-build` gets stuck here.

```
evaluating file '/nix/store/gvl1kcvqwq8kddg9rh4wlf68lgx89z5x-nixpkgs-21.05pre273332.5df05c902cd/nixpkgs/pkgs/build-support/rust/hooks/default.nix'
evaluating file '/nix/store/gvl1kcvqwq8kddg9rh4wlf68lgx89z5x-nixpkgs-21.05pre273332.5df05c902cd/nixpkgs/pkgs/build-support/remove-references-to/default.nix'
evaluating file '/nix/store/gvl1kcvqwq8kddg9rh4wlf68lgx89z5x-nixpkgs-21.05pre273332.5df05c902cd/nixpkgs/pkgs/build-support/rust/fetchCargoTarball.nix'
downloading 'https://github.com/sayanarijit/xplr/archive/refs/tags/v0.3.2.tar.gz'...
unpacking 'https://github.com/sayanarijit/xplr/archive/refs/tags/v0.3.2.tar.gz'...
these derivations will be built:
  /nix/store/52mb2icxw3a9za6w54803l8mls5xclzw-xplr-vendor.tar.gz.drv
  /nix/store/aiqmdjyb72795927sh0g1vzsqlsjjmpi-xplr.drv
building '/nix/store/52mb2icxw3a9za6w54803l8mls5xclzw-xplr-vendor.tar.gz.drv'...
unpacking sources
unpacking source archive /nix/store/0gp539zx3wdzmb8k9yc9282dvv317i48-source
source root is source
patching sources
building
    Updating crates.io index
```

**Comment by GuilloteauQ** [comment]
it takes a little bit of time indeed, but it should not block

**Comment by sayanarijit** [comment]
It's not working. Unfortunately I'll need a better workflow. Is it possible to some how update the nix hash via [gh action](https://github.com/sayanarijit/xplr/blob/main/.github/workflows/ci.yml) when I create a PR?

**Comment by sayanarijit** [comment]
@GuilloteauQ You'll be happy to know that `xplr` has been added to [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/xplr/default.nix).

**Pull request merged**
