### PR TITLE
Fix focus jumping

### PR DESCRIPTION
**Pull request by sayanarijit**
Fixes: https://github.com/sayanarijit/xplr/issues/211

### CODE REVIEW

**Comment by sayanarijit** [comment]
delete-n-focus

**Comment by sayanarijit** [comment]
@maximbaz I went through your dotfiles and found you're not using verbosity for deletion. In that case, you can use `BashExecSilently` instead which is non-intercative and will feel anappier.

**Comment by maximbaz** [comment]
Ooh so true, thank you! This really feels awesome by the way, that focus stays where it should be 👍

**Comment by sayanarijit** [comment]
Another unrelated minor improvement: You don't to execute BashExec... to send ChangeDirectory message. You can send it directly if it doesn't read env variables.

**Comment by maximbaz** [comment]
Of course.... many thanks :)

**Pull request merged**
