### PR TITLE
Add support for native lua bindings

### PR DESCRIPTION
**Pull request by sayanarijit**
Ref: https://github.com/sayanarijit/xplr/discussions/146#discussioncomment-741580

### CODE REVIEW

**Comment by sayanarijit** [comment]
Syntax:

```
config.version = 'v0.9.1'

config.general.default_ui.prefix = ' '
config.general.default_ui.suffix = ''

config.general.focus_ui.prefix = '▸'
config.general.focus_ui.suffix = ''
config.general.focus_ui.style.fg = { Rgb = { 170, 150, 130 } }
config.general.focus_ui.style.bg = { Rgb = { 50, 50, 50 } }
config.general.focus_ui.style.add_modifiers = { 'Bold' }

-- Remaps
config.modes.builtin.default.key_bindings.on_key.e = config.modes.builtin.action.key_bindings.on_key.e
```

**Comment by maximbaz** [comment]
This is looking quite interesting! Considering that you have it easier with lua, that plugins will probably also be written in lua, I think this is the right one to proceed with.

**Comment by sayanarijit** [comment]
I think `init.lua` will make more sense here because it's not a plain config file anymore.

**Comment by sayanarijit** [comment]
Need some more time to explore the possibilities. With lua native support, I think we can drop the handlebars syntax and define it as a lua function. There might be other areas we can improve with lua.

**Comment by sayanarijit** [comment]
I'm not getting much time to work on this. So, I'll secretly release a beta version, while maintaining `yaml` compatibility. So that people living on the edge can try it out and probably move from `yaml` to `lua` gradually. I think it's better to gradually keep the integration happening than doing all at once in a big release.

**Comment by sayanarijit** [comment]
We'll also need to migrate the [config.yml](https://github.com/sayanarijit/xplr/blob/main/src/config.yml) to lua. Contributions welcome.

Tip: Lua's multiline string support is awesome..

```lua
BashExec: [===[
     ls -l
]===]
```

**Comment by sayanarijit** [comment]
Release discussion: https://github.com/sayanarijit/xplr/releases/tag/v0.10.0-beta.0

**Pull request merged**
