### PR TITLE
Add support for un-mapping keys.

### PR DESCRIPTION
**Pull request by sayanarijit**
Use `remaps: {key: null}` to un-map a key.

Also,
- `gx` will now open only the file under focus.
- `:sx` will open the selected files.

And other minor improvements.

### CODE REVIEW

**Comment by sayanarijit** [comment]
@maximbaz

```yaml
remaps:
  a: ctrl-a
  V: null
  ctrl-a: null
```
This should work fine now.

**Comment by maximbaz** [comment]
Nice!

maybe a new bug, maybe not: in a folder with broken symlink, `ctrl-a` doesnt select broken symlink and doesnt _toggle_ selection.

**Comment by sayanarijit** [comment]
I think it should be an old bug. Will fix it.

**Comment by maximbaz** [comment]
And another bug (or rather super edge case 😅 ):

    search:
      key_bindings:
        remaps:
          ctrl-p: tab
          tab: right

Basically I want to swap around a few of the pre-defined keys. This makes the behavior correct, but `ctrl-p` is not in the help list.

**Comment by sayanarijit** [comment]
Hmm, I'll need to implement some sort of remap resolution logic.

**Pull request merged**
