### PR TITLE
Improve key inputs

### PR DESCRIPTION
**Pull request by sayanarijit**
Add support proper implementations of -

- backspace
- ctrl-w
- ctrl-u

Also, improved sort and filter behavior.

Fixes: https://github.com/sayanarijit/xplr/issues/77

### CODE REVIEW

**Comment by sayanarijit** [comment]
@maximbaz wasn't too hard :smile:

**Comment by sayanarijit** [comment]
Tested. Merging this. @maximbaz let me know if you find any miss.

**Comment by maximbaz** [comment]
Nice, just tested too, seems fine!

**Comment by maximbaz** [comment]
Actually, one issue is that space to toggle selection doesn't work anymore 😅

**Comment by sayanarijit** [comment]
https://github.com/sayanarijit/xplr/pull/82

**Pull request merged**
