### PR TITLE
Use fuzzy search instead of regex search

### PR DESCRIPTION
**Pull request by sayanarijit**
Closes: https://github.com/sayanarijit/xplr/issues/496
Closes: https://github.com/sayanarijit/xplr/issues/500

### CODE REVIEW

**Comment by sayanarijit** [comment]
Let's allow customizable search config?

**Comment by sayanarijit** [comment]
Todo fix doc

**Comment by roland-rollo** [comment]
Sorry for spam comment, but I tried build it with `cargo install --git "https://github.com/sayanarijit/xplr" --branch "add-fzy-search"`
and it shows me this:
```
    Updating git repository `https://github.com/sayanarijit/xplr`
  Installing xplr v0.19.4 (https://github.com/sayanarijit/xplr?branch=add-fzy-search#9b4524cd)
    Updating crates.io index
  Downloaded anyhow v1.0.65
  Downloaded serde v1.0.145
  Downloaded thiserror v1.0.37
  Downloaded thiserror-impl v1.0.37
  Downloaded serde_derive v1.0.145
  Downloaded unicode-width v0.1.10
  Downloaded unicase v2.6.0
  Downloaded unicode-segmentation v1.10.0
  Downloaded yaml-rust v0.4.5
  Downloaded linked-hash-map v0.5.6
  Downloaded mime_guess v2.0.4
  Downloaded once_cell v1.15.0
  Downloaded proc-macro2 v1.0.46
  Downloaded cassowary v0.3.0
  Downloaded ansi-to-tui v2.0.0
  Downloaded erased-serde v0.3.23
  Downloaded crossterm v0.25.0
  Downloaded natord v1.0.9
  Downloaded humansize v2.0.0
  Downloaded fuzzy-matcher v0.3.7
  Downloaded mlua v0.8.3
  Downloaded gethostname v0.2.3
  Downloaded dirs v4.0.0
  Downloaded rustc-hash v1.1.0
  Downloaded tui v0.18.0
  Downloaded tui-input v0.5.1
  Downloaded tui v0.19.0
  Downloaded iana-time-zone v0.1.50
  Downloaded crossterm v0.23.2
  Downloaded serde_yaml v0.8.26
  Downloaded lock_api v0.4.9
  Downloaded libm v0.2.5
  Downloaded syn v1.0.101
  Downloaded libc v0.2.134
  Downloaded lua-src v544.0.1
  Downloaded luajit-src v210.4.3+resty8384278
  Downloaded 36 crates (4.2 MB) in 1.16s (largest was `luajit-src` at 1.1 MB)
   Compiling autocfg v1.1.0
   Compiling libc v0.2.134
   Compiling proc-macro2 v1.0.46
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.4
   Compiling syn v1.0.101
   Compiling serde_derive v1.0.145
   Compiling cfg-if v1.0.0
   Compiling serde v1.0.145
   Compiling version_check v0.9.4
   Compiling memchr v2.5.0
   Compiling log v0.4.17
   Compiling parking_lot_core v0.9.3
   Compiling signal-hook v0.3.14
   Compiling smallvec v1.9.0
   Compiling scopeguard v1.1.0
   Compiling bitflags v1.3.2
   Compiling cc v1.0.73
   Compiling once_cell v1.15.0
   Compiling erased-serde v0.3.23
   Compiling unicode-width v0.1.10
   Compiling pkg-config v0.3.25
   Compiling thiserror v1.0.37
   Compiling unicode-segmentation v1.10.0
   Compiling libm v0.2.5
   Compiling cassowary v0.3.0
   Compiling hashbrown v0.12.3
   Compiling linked-hash-map v0.5.6
   Compiling anyhow v1.0.65
   Compiling minimal-lexical v0.2.1
   Compiling rustc-hash v1.1.0
   Compiling mime v0.3.16
   Compiling ryu v1.0.11
   Compiling iana-time-zone v0.1.50
   Compiling regex-syntax v0.6.27
   Compiling natord v1.0.9
   Compiling lazy_static v1.4.0
   Compiling lock_api v0.4.9
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling indexmap v1.9.1
   Compiling unicase v2.6.0
   Compiling thread_local v1.1.4
   Compiling luajit-src v210.4.3+resty8384278
   Compiling lua-src v544.0.1
   Compiling tui v0.19.0
   Compiling yaml-rust v0.4.5
   Compiling fuzzy-matcher v0.3.7
   Compiling mlua v0.8.3
   Compiling signal-hook-registry v1.4.0
   Compiling dirs-sys v0.3.7
   Compiling time v0.1.44
   Compiling gethostname v0.2.3
   Compiling mio v0.8.4
   Compiling aho-corasick v0.7.19
   Compiling bstr v0.2.17
   Compiling nom v7.1.1
   Compiling humansize v2.0.0
   Compiling dirs v4.0.0
   Compiling parking_lot v0.12.1
   Compiling regex v1.6.0
   Compiling mime_guess v2.0.4
   Compiling signal-hook-mio v0.2.3
   Compiling crossterm v0.23.2
   Compiling crossterm v0.25.0
   Compiling thiserror-impl v1.0.37
   Compiling ansi-to-tui v2.0.0
   Compiling chrono v0.4.22
   Compiling tui-input v0.5.1
   Compiling tui v0.18.0
   Compiling serde_yaml v0.8.26
   Compiling xplr v0.19.4 (/home/roland/.cargo/git/checkouts/xplr-9988ed47e4260dd9/9b4524c)
error[E0308]: mismatched types
  --> src/ui.rs:47:33
   |
47 |             .unwrap_or_else(|e| Text::raw(format!("{:?}", e)))
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `tui::text::Text`, found a different struct `tui::text::Text`
   |
   = note: perhaps two different versions of crate `tui` are being used?

error[E0308]: mismatched types
  --> src/ui.rs:44:9
   |
40 |   fn string_to_text<'a>(string: String) -> Text<'a> {
   |                                            -------- expected `tui::text::Text<'a>` because of return type
...
44 | /         string
45 | |             .as_bytes()
46 | |             .into_text()
47 | |             .unwrap_or_else(|e| Text::raw(format!("{:?}", e)))
   | |______________________________________________________________^ expected struct `tui::text::Text`, found a different struct `tui::text::Text`
   |
   = note: perhaps two different versions of crate `tui` are being used?

For more information about this error, try `rustc --explain E0308`.
error: could not compile `xplr` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `xplr v0.19.4 (https://github.com/sayanarijit/xplr?branch=add-fzy-search#9b4524cd)`, intermediate artifacts can be found at `/tmp/cargo-installJBJBFc`
```

Is it problem on my side?

**Comment by sayanarijit** [comment]
No, I also get this with `install` command. `build` works fine. I thought it was specific to me, thanks for reporting.

**Comment by sayanarijit** [comment]
It's a version mismatch bug. Will fix this just before the release.

**Pull request merged**
