### PR TITLE
Add xplr.util.relative_to and xplr.util.path_shorthand

### PR DESCRIPTION
**Pull request by noahmayr**
Adds two utility functions mentioned and discussed in #564

### CODE REVIEW

**Comment by sayanarijit** [comment]
- Instead of using dirs, I think it'd be faster to just read $HOME.
- Does rust side also return the initial dir on querying $PWD?

**Comment by sayanarijit** [comment]
pathdiff is a simple and small function, so I don't think we should add it as a new dependency.

I'd implement it myself or copy the code mentioning the source in a comment, as done in permissions.rs

**Comment by sayanarijit** [comment]
> - ~Does rust side also return the initial dir on querying $PWD?~ yes.

But interestingly, `std::env::current_dir()` works fine.

**Comment by noahmayr** [comment]
> * Instead of using dirs, I think it'd be faster to just read $HOME.

I'm not sure the impact is that big, since I'm only reading the home dir once

**Comment by noahmayr** [comment]
I've updated it to use `std::env::current_dir()` as a fallback and changed the target branch to dev.

**Comment by sayanarijit** [comment]
Ignore the clippy errors. Will review soon.

**Comment by sayanarijit** [comment]
I pushed some changes. Could you pls review this?

**Comment by sayanarijit** [comment]
I think instead of `.`, it's better to display `../pwd`. Same for `..`, `../..` etc. Since it's better to display the name of the dir.

**Comment by noahmayr** [comment]
image
I'm not sure if I actually find this more clear than just `..`

image
In this case you can tell directly that it's pointing to the parent directory.

What do you think about adding an additional optional flag like `ensure_path_includes_filename`? (or ideally some less verbose parameter name)

**Comment by sayanarijit** [comment]
`basename_must` can default to false.

**Comment by sayanarijit** [comment]
2 optional arguments is difficult for Lua, So, I guess 2nd argument should be a table.

**Comment by noahmayr** [comment]
I actually don't think it's that bad: `xplr.util.shortened(n.absolute_path, nil, true)`. I think using a table actually complicates the api here: `xplr.util.shortened(n.absolute_path, { base = "/bin", basename_must = true })`

I'm trying out your changes right now, what do you think about prefixing relative paths (assuming they don't start with `..` or '.' with a './'  so for example `./somedir`. I think the selection list can get a bit confusing when you have entries like `/home` along with `somedir`. Just to make it more explicit that the path is relative to the current dir

**Comment by noahmayr** [comment]
Unless we want it more configurable with this prefixing being a separate option from `basename_must`, then the table argument starts to make more sense

**Comment by sayanarijit** [comment]
> I actually don't think it's that bad: xplr.util.shortened(n.absolute_path, nil, true)

I think being explicit is better when we have more than 2 unnamed arguments.

> I'm trying out your changes right now, what do you think about prefixing relative paths (assuming they don't start with .. or '.' with a './' so for example ./somedir. I think the selection list can get a bit confusing when you have entries like /home along with somedir. Just to make it more explicit that the path is relative to the current dir

Good point.

**Comment by noahmayr** [comment]
I've added some additional handling for edge cases where we didn't actually show the filename in the shortened path and moved the rendering of the selection list items to lua.

**Comment by sayanarijit** [comment]
Pushed some more improvements. I think we're close enough.

**Comment by sayanarijit** [comment]
Merging this. But let's continue testing this and find more edge cases.

**Pull request merged**
