### PR TITLE
Some refactors

### PR DESCRIPTION
**Pull request by dtomvan**
I Refactored parts of `runner::Runner` to take a Cli struct, instead of putting everything manually in `Runner`.
This is what you want to use most of the time. Otherwise your stuck with a lot of 
```rs
.and_then(|a| a.yyy(xxx))
```
in `xplr::runner::Runner`.

### CODE REVIEW

**Comment by sayanarijit** [comment]
Hey, thanks. I'll review soon.

**Comment by sayanarijit** [comment]
Conceptually looks good. I'll make some minor changes.

**Comment by sayanarijit** [comment]
Yes https://github.com/sayanarijit/xplr/issues/39. But try to avoid the temptation of aiming for too big of a refactor. One function at a time is what I consider ideal. We can also apply TDD this way (though in this case the logic is already written). Have fun :cheese:

**Comment by dtomvan** [comment]
Yeah, I'll just write 1 test per commit as a guideline, and apply tdd to it. Sounds good. This works well as a side project I guess.

**Pull request merged**
