### PR TITLE
Add/timestamp

### PR DESCRIPTION
**Pull request by sayanarijit**

### CODE REVIEW

**Comment by sayanarijit** [comment]
There's some non trivial performance drop.

```
     Running unittests (target/release/deps/criterion-231b41e6c56f74dd)
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

focus next item         time:   [4.0281 ms 4.0322 ms 4.0363 ms]
                        change: [+23.735% +23.914% +24.097%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

focus previous item     time:   [4.4112 ms 4.4175 ms 4.4241 ms]
                        change: [+27.816% +28.043% +28.259%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low mild
  3 (3.00%) high mild

focus first item        time:   [8.6160 ms 8.6277 ms 8.6396 ms]
                        change: [+34.195% +34.444% +34.677%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

focus last item         time:   [4.4397 ms 4.4458 ms 4.4523 ms]
                        change: [+26.531% +26.754% +26.986%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  1 (1.00%) high severe

leave and enter directory
                        time:   [9.3207 ms 9.3322 ms 9.3441 ms]
                        change: [+37.194% +37.397% +37.611%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild
```

**Comment by sayanarijit** [comment]
@sux2mfgj I also added `created` timestamp (since only `last_modified` feel a bit odd) and did the benchmark multiple times, but found the same (~25%) drop in performance. I'm not sure if it's worth, so I'm going to close the PR. But if you have a use case that can justify the compromise, feel free to reopen.

**Comment by sux2mfgj** [comment]
Sorry I forgot it. Thanks.

**Comment by sayanarijit** [comment]
Closing wrt https://github.com/sayanarijit/xplr/pull/476

**Pull request closed without merging**
