### PR TITLE
Added inode size

### PR DESCRIPTION
**Pull request by sayanarijit**
Also supports sorting by inode size.

Closes: https://github.com/sayanarijit/xplr/issues/84

### CODE REVIEW

**Comment by sayanarijit** [comment]
image

**Comment by sayanarijit** [comment]
image

**Comment by sayanarijit** [comment]
Merging this. Let me know if all is ok.

**Comment by maximbaz** [comment]
Wow you are fast!

Love the new design, very nice! 

Just thinking if we should hide sizes of directories altogether (like exa does), since they are not what users would normally expect anyway. What do you think?

**Pull request merged**
