### PR TITLE
Timestamp support

### PR DESCRIPTION
**Pull request by sux2mfgj**
Screen Shot 2021-10-31 at 17 46 33

### CODE REVIEW

**Comment by sux2mfgj** [comment]
Implement for an issue #390.

**Comment by sayanarijit** [comment]
Thanks for the PR. Big help :+1:

**Comment by igorepst** [comment]
Although I 100% want the time support, I would like to ask whether `human_modified` (and, actually, `human_size`) should exist as them. Because the hardcoded formatting may not be suitable for everyone (here, as far as I see, it is not possible to show year), so why to pay performance penalty for calculation? (I may be wrong, if this is called lazily, I don't actually know Rust). Thanks!

**Comment by sayanarijit** [comment]
The human formatted size and time are just for convenience. Anyone can calculate from the other alternative. I guess this will add some performance cost, but I'll make sure to measure it. Especially in slower machines. If there's significant performance drop, we can research other workarounds.

**Comment by sux2mfgj** [comment]
The `human_modified` implementation is refered the `human_size`. About the performance I think you are right, but, I also have a lack of rust experience. We need a comment from the committers.

Thanks a lot.

**Comment by sayanarijit** [comment]
BTW, you can measure it too using `cargo bench`.

**Comment by sayanarijit** [comment]
Continuing in https://github.com/sayanarijit/xplr/pull/423

**Pull request closed without merging**
