### PR TITLE
Improve scrolling behaviour

### PR DESCRIPTION
**Pull request by sayanarijit**
Closes: https://github.com/sayanarijit/xplr/issues/54

### CODE REVIEW

**Comment by sayanarijit** [comment]
xplr-scrolling

**Comment by sayanarijit** [comment]
@maximbaz how do you like this one?

**Comment by maximbaz** [comment]
It's interesting, definitely better! Personally I think I prefer the nnn/vim approach as I think it's more "dynamic", especially if you will be working with files that are on the "edge", e.g. the bottom two and the top two on the next page, you will be jumping up and down all the time and it may be a bit more difficult to grasp a whole "context". 🤔 

And yay it takes the full height now, great 👍

**Comment by sayanarijit** [comment]
Yes the vim like navigation would be great. But that requires extra state management which I want to avoid diving into for now. I'll keep this issue open so that if someone wantsto give this a shot, they'll get a starting point.

**Pull request merged**
