### PR TITLE
Implement support path selection and force focus

### PR DESCRIPTION
**Pull request by sayanarijit**
Examples:

```bash
xplr $PWD /path/to/select1 path/to/select2

xplr -- $PWD /path/to/select1 path/to/select2

echo -e "$PWD\n/path/to/select1\npath/to/select2" | xplr -

ls -d /path/to/select1 path/to/select2 | xplr $PWD -
```

### CODE REVIEW

**Comment by sayanarijit** [comment]
@dtomvan could you please test and review?

**Comment by dtomvan** [comment]
Bug: https://asciinema.org/a/WePaZ7uT4L4gch4zc8jsexH7T

The selection seems to disappear when pressing j or k.

**Comment by sayanarijit** [comment]
Glad I asked :D

**Comment by dtomvan** [comment]
Also, I noticed that if you pass a flag that doesn't exist, then it doesn't error. That is because it interprets anything that isn't a `match` branch as a path. But then it still doesn't error on "... doesn't exist" or something like that. Even passing `xplr asdf` does not error, and `xplr --force-focus asdf` focuses the parent of $PWD.

**Comment by sayanarijit** [comment]
> Also, I noticed that if you pass a flag that doesn't exist, then it doesn't error. That is because it interprets anything that isn't a `match` branch as a path. But then it still doesn't error on "... doesn't exist" or something like that.

Good point. Will fix.

> xplr --force-focus asdf focuses the parent of $PWD.

Shouldn't happen, couldn't reproduce.

**Comment by dtomvan** [comment]
> > xplr --force-focus asdf focuses the parent of $PWD.
> 
> Shouldn't happen, couldn't reproduce.

I just did a git pull and it is working now.

**Comment by sayanarijit** [comment]
Hope all fixed now. Merging this.

**Pull request merged**
