### PR TITLE
Fix distorted screen when opening files in GUI

### PR DESCRIPTION
**Pull request by sayanarijit**
Fixes: https://github.com/sayanarijit/xplr/issues/111

### CODE REVIEW

**Comment by sayanarijit** [comment]
@aflyingpumpkin can you pls test if this works for you?

**Comment by sayanarijit** [comment]
Also @maximbaz, @suryasr007, @aflyingpumpkin need your review.

**Comment by aflyingpumpkin** [comment]
One sec though the error was fixed for me whenever the disowning was fixed

**Comment by sayanarijit** [comment]
Ah sorry pinged you twice.

**Comment by aflyingpumpkin** [comment]
Its fine, but how do I test a PR? (I'm new to git)

**Comment by sayanarijit** [comment]
@auronandace can you pls test if this fix works for you?

**Comment by sayanarijit** [comment]
[xplr.tar.gz](https://github.com/sayanarijit/xplr/files/6386470/xplr.tar.gz)

**Comment by sayanarijit** [comment]
^ Here's the linux binary

```
➜ wget https://github.com/sayanarijit/xplr/files/6386470/xplr.tar.gz
➜ md5sum xplr.tar.gz
f8d13d5c9daa545c634e015a99f017b2  xplr.tar.gz
➜ tar xvzf xplr.tar.gz
➜ ./xplr
```

**Comment by sayanarijit** [comment]
Ah sorry wrong binary. will upload again.

**Comment by sayanarijit** [comment]
[xplr.tar.gz](https://github.com/sayanarijit/xplr/files/6386491/xplr.tar.gz)

```
➜  wget https://github.com/sayanarijit/xplr/files/6386491/xplr.tar.gz
➜  md5sum xplr.tar.gz
2e594f6c6ccbbc7a059c9e09ce79373b  xplr.tar.gz
➜ tar xvzf xplr.tar.gz
➜ ./xplr
```

**Comment by sayanarijit** [comment]
For @suryasr007, you have to compile :P

**Comment by auronandace** [comment]
./xplr: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by ./xplr)

**Comment by aflyingpumpkin** [comment]
For me the issue in #111 is fixed by having
```
                  ${OPENER:-open} "${XPLR_FOCUS_PATH:?}" &> /dev/null &
                  disown || true
```
in the config, though updating to this PR does not hurt it.  But, when I remove the disown from the config it will still have the glitchy UI even on the new version though.

**Comment by aflyingpumpkin** [comment]
Wait just realized that my config hadn't changed. Let me go update it.

**Comment by aflyingpumpkin** [comment]
Just updated my config to the PR. This does fix the issue.

**Comment by sayanarijit** [comment]
For @auronandace can you install rust?
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by sayanarijit** [comment]
Once installed,

```
git clone https://github.com/sayanarijit/xplr
cd xplr
cargo run --release
```

**Comment by auronandace** [comment]
Doesn't that just run 5.7 (which is what I was already running)?

The problem still persists.

**Comment by sayanarijit** [comment]
Ah sorry, missed one little command

```
git checkout fix/gui-opener-111
cargo run --release
```

**Comment by auronandace** [comment]
Excellent! Problem solved. xplr now redraws properly.

**Comment by sayanarijit** [comment]
Also tested in Mac (luckily my powerbank was able to charge it). Shipping it.

**Pull request merged**
