### PR TITLE
Add filter key binding

### PR DESCRIPTION
**Pull request by sayanarijit**
Use `f` to set relative path filter.

### CODE REVIEW

**Comment by sayanarijit** [comment]
@maximbaz here I added partly `nnn` like filter in the default key binding. But unlike `nnn` you have to manually reset the applied filters.

**Comment by maximbaz** [comment]
I think this is perfect, very intuitive! And you can even build multiple filters, instead of coming up with some fancy regex, very very nice!

**Comment by sayanarijit** [comment]
Also make search and filter case insensitive.

**Comment by maximbaz** [comment]
I only have a small comment on the behavior of Backspace, but let me make a separate thread for that, this PR I like very much!

**Pull request merged**
