### PR TITLE
add node owner user and group

### PR DESCRIPTION
**Pull request by Junker**

### CODE REVIEW

**Comment by sayanarijit** [comment]
Thanks for the pr. We may need to add the same in ResolvedNode too.

**Comment by Junker** [comment]
> We may need to add the same in ResolvedNode too.

Then we also need to add permissions to ResolvedNode too. I think this should be in another PR.

**Comment by sayanarijit** [comment]
Ah, right... Don't never mind.

**Comment by sayanarijit** [comment]
Benchmark doesn't look very good... Can we somehow optimize this? We're using https://github.com/bheisler/criterion.rs for benchmarks.

**Comment by sayanarijit** [comment]
Also, maybe we can avoid adding a dependency by adding a single file like: https://github.com/sayanarijit/xplr/blob/main/src/permissions.rs

**Comment by sayanarijit** [comment]
I was thinking, do we really need to load the user and group names in rust?
I think it'd be better to just read the uid and gid in rust, and whoever needs, can parse the passwd file in lua and build up cache in lua. The user and group name resolution can be offloaded to lua like we do with the timestamps

**Pull request closed without merging**
